### ISSUE TITLE
Returned Dockerfile completions are lower-cased

### ISSUE THREAD

**Issue by nrvale0** [nrvale0/company-dockerfile#1]
By lifting some code from [this](http://sixty-north.com/blog/writing-the-simplest-emacs-company-mode-backend) blog post, I was able to implement a simple completion mode for Dockerfiles. Everything works as expected when running Emacs in an X session however when running as 'emacs -nw' the returned completions are lower-cased despite the fact that the proposed completion lists items are all [upper-cased](https://github.com/nrvale0/company-dockerfile/blob/master/company-dockerfile.el#L3).

This is sort of an unusual way of requesting assistance but I'm hoping the author of Company(@dgutov) or the author of the blogpost(@abingham) can provide some tips on how to make the proposed completions be upper-cased?

**Comment by abingham** [comment]
I've tried to replicate this, but as far as I can tell your backend isn't lower-casing things in `-nw` mode. FWIW, that post is pretty old and might be out of date on important details.

**Comment by nrvale0** [comment]
@abingham After a stop of all Emacs instances and a restart in -nw I can't repro it either. I really appreciate you taking a look!
